#!/bin/bash

if [ "$1" == "run" ]; then 
    eval $(opam env)
    args=($@)
    arr=("${args[@]:1}")
    dune build && dune exec ./bin/main.exe $arr
elif [ "$1" == "test" ]; then
    eval $(opam env)
    dune test
elif [ "$1" == "build" ]; then
    eval $(opam env)
    dune build
else
    echo "command not recognized"
fi

